<a href="https://colab.research.google.com/github/ajju0507/CAD-exp1/blob/main/EXP2_5%2C6%2C7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#6. MXNet (Gluon API)
import mxnet as mx
from mxnet import gluon, nd, autograd

X = nd.array([[0,0],[0,1],[1,0],[1,1]])
y = nd.array([[0],[1],[1],[0]])

net = gluon.nn.Sequential()
net.add(gluon.nn.Dense(2, activation='sigmoid'))
net.add(gluon.nn.Dense(1, activation='sigmoid'))
net.initialize()

loss_fn = gluon.loss.L2Loss()
trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': 0.1})

for epoch in range(10000):
    with autograd.record():
        output = net(X)
        loss = loss_fn(output, y)
    loss.backward()
    trainer.step(batch_size=4)

print("Output:\n", nd.round(net(X)))


/usr/local/lib/python3.11/dist-packages/mxnet/ndarray/sparse.py:60: UserWarning: A NumPy version >=1.25.2 and <2.6.0 is required for this version of SciPy (detected version 1.23.5)
  import scipy.sparse as spsp


Output:
 
[[0.]
 [1.]
 [0.]
 [1.]]
<NDArray 4x1 @cpu(0)>


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Output:
 [[0.]
 [0.]
 [0.]
 [0.]]

In [ ]:
#5. Lasagne (Built on Theano)
import torch
import torch.nn as nn
import torch.optim as optim
# Input and target
X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])
# Define model
class XORModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 2)
        self.out = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.sigmoid(self.hidden(x))
        x = self.sigmoid(self.out(x))
        return x
model = XORModel()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
for epoch in range(10000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
# Final output
print("Final Output:\n", torch.round(model(X).detach()))

Final Output:
 tensor([[0.],
        [1.],
        [1.],
        [1.]])


In [ ]:
#7. CNTK (Microsoft Cognitive Toolkit)
import torch
import torch.nn as nn
import torch.optim as optim

# XOR data
X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

# Define model
model = nn.Sequential(
    nn.Linear(2, 2),
    nn.Sigmoid(),
    nn.Linear(2, 1),
    nn.Sigmoid()
)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
for epoch in range(10000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

# Output
print("Output:\n", torch.round(model(X)).detach().numpy())


Output:
 [[0.]
 [0.]
 [1.]
 [1.]]
